### ISSUE TITLE
1.2.3 still having cosmetics shown at wrong height issue

### ISSUE THREAD

**Issue by Pattanawaris** [PluginBugs/Issues-CosmeticsCore#173]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

issue from https://github.com/PluginBugs/Issues-CosmeticsCore/issues/168 is still exist in 1.2.3 with all dependencie plugins updated

### Steps to reproduce the issue

Wear some cosmetic.
Left Wardrobe.
Change game view mode to third person view.

### Server version

git-paper-259

### CosmeticsCore Version

1.2.3

### ProtocolLib Version

5.1.1 -Snapshot - 673

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
Please refer to the new tutorials
https://cosmeticscore.devs.beer/adding-content/body-cosmetic/static-body-cosmetic#implementing-the-self-models

You have to implement the self model 2, which I implemented to the default pack, you can get it in the `default_assets.zip` file under the CosmeticsCore folder (delete this file and restart if you can't get the updated one).

**Comment by Pattanawaris** [comment]
Yes but, how about If I didnt use Self model method pls?

**Comment by LoneDev6** [comment]
It should look just fine if you don't use selfmodel, it was tested and working with default items.

**Comment by Pattanawaris** [comment]
It still having issue :( . even in global view other players are saw it displayed at the wrong height too.
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/22558449/8a9c88dc-480c-4d21-ab6c-d6c21dc1c5ef)

**Comment by Pattanawaris** [comment]
More info: item displayed fine when first loaded(instant after teleported or join) then quickly lifted up to the wrong height one and stay at the wrong height.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
Please provide an example CosmeticsCore yml file and the json models files for normal, self and self2 cosmetics.
Also provide the 3 .bbmodel files.

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/27242001/354e5b1f-84de-41a0-b6d1-238d99644fb9

---

NOTE: do you have any plugin which is adding nametags on top of the player? (as invisible armorstands riding the player)
It might be the issue.

**Comment by WindUnwaken** [comment]
https://youtu.be/ZADrU2N9kQs

Please also check normal view

**Comment by WindUnwaken** [comment]
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/19383943/4a7c62d1-e93b-46c8-ba5f-85b1e3241332)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/19383943/2733d2fc-9d89-4e01-b6a2-0854afb13ced)
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/19383943/fbe399b7-4cb4-442b-a9a8-4d03905c31b7)

Outside the wardrobe, armorstand is on the top of head,
In the wardobe, near the shoulder, maybe also make normal_2?

**Comment by WindUnwaken** [comment]
https://youtu.be/sozM-UXstpQ

**Comment by iFranticman** [comment]
I'm having the same issues where my cosmetics are higher than normal. Other players can see it just fine but when i go into f5 i see them high. I use only elite creatures and it's on every cosmetic cape.

**Comment by LoneDev6** [comment]
Please next time post a video to begin with.
I now see that your issue is that the issue is reproducible on viewers of other players.

I will have to fix the Blockbench extension and the plugin too.

**Comment by LoneDev6** [comment]
It is related to 1.20.2.
I am going to publish a fix today for both bb extension and Spigot plugin.

**Comment by iFranticman** [comment]
When i updated i got this 
[12:51:37 WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.2-beta-r4 generated an exception while executing task 276
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter(org.bukkit.command.TabCompleter)
" because the return value of "dev.lone.itemsadder.Main.a(String)" is null
        at ia.m.hs.<init>(SourceFile:80) ~[ItemsAdder_3.6.2-beta-r4.jar:?]
        at ia.m.G.a(SourceFile:921) ~[ItemsAdder_3.6.2-beta-r4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-280]
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-280]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.j
ar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by LoneDev6** [comment]
Please do not report multiple issues on other issue pages.
Anyway this is not related to CosmeticsCore, post your complete server log in a new issue report on ItemsAdder Github.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/

**Comment by Pattanawaris** [comment]
I think I'm still having this issue in latest version :( 

in wardrobe:
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/22558449/564e2579-0d92-4e1f-bd6a-42cfd70390d9)

outside wardrobe:
![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/22558449/abc6fdfd-864c-4f8a-b2c4-e92823d2579b)

**Comment by aaa8881** [comment]
If I'm not mistaken, am I supposed to make self2 model to every body cosmetics to make it look normal?

**Comment by aaa8881** [comment]
I'm still having difficulty to make this one working in 1.20.2+ 

sorry for ping @LoneDev6 , pinging as it's old thread and you will prob miss it without it. 

only self view in 1.20.2+ is the problem.
self and self_2 model are generated based on normal model , and normal_2 model also exists. 

unsure if we're generating self_2 model incorrectly. 

1. should self_2 model generated from normal model?
